import type { Level } from '@/lib/levels';

/**
 * ── THE FREE RUN — GENERATED, DO NOT EDIT ──────────────────────────
 *
 * Written by `node scripts/build-levels.mjs` from `scripts/levels.source.mjs`.
 * Edit the source and re-run; edits here are lost on the next build.
 *
 * 50 levels. `level` is 1-based within its own bank and permanent: it is
 * the number on the map, the key progress is stored under, and the thing a
 * player says out loud. **Append only.** Inserting a level renumbers every one
 * after it and rewrites the history of everyone playing.
 *
 * Difficulty is derived, never hand-written — PRD §3.2. Run
 * `scripts/puzzle-check.mjs` for the two things no heuristic can decide:
 * uniqueness and real corpus frequency.
 */
export const LEVELS: Level[] = [
  { id: 'L-001', level: 1, answer: 'book', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'case', position: 'after' }, { text: 'note', position: 'before' }, { text: 'mark', position: 'after' }] },
  { id: 'L-002', level: 2, answer: 'ball', accepted: [],
    difficulty: 1, category: 'category.play',
    words: [{ text: 'foot', position: 'before' }, { text: 'room', position: 'after' }, { text: 'snow', position: 'before' }] },
  { id: 'L-003', level: 3, answer: 'moon', accepted: [],
    difficulty: 1, category: 'category.sky',
    words: [{ text: 'light', position: 'after' }, { text: 'honey', position: 'before' }, { text: 'beam', position: 'after' }] },
  { id: 'L-004', level: 4, answer: 'side', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'walk', position: 'after' }, { text: 'out', position: 'before' }, { text: 'road', position: 'before' }] },
  { id: 'L-005', level: 5, answer: 'time', accepted: [],
    difficulty: 1, category: 'category.time',
    words: [{ text: 'table', position: 'after' }, { text: 'some', position: 'before' }, { text: 'life', position: 'before' }] },
  { id: 'L-006', level: 6, answer: 'paper', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'news', position: 'before' }, { text: 'back', position: 'after' }, { text: 'wall', position: 'before' }] },
  { id: 'L-007', level: 7, answer: 'line', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'life', position: 'before' }, { text: 'on', position: 'before' }, { text: 'up', position: 'after' }] },
  { id: 'L-008', level: 8, answer: 'work', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'home', position: 'before' }, { text: 'shop', position: 'after' }, { text: 'net', position: 'before' }] },
  { id: 'L-009', level: 9, answer: 'bird', accepted: [],
    difficulty: 2, category: 'category.animals',
    words: [{ text: 'black', position: 'before' }, { text: 'house', position: 'after' }, { text: 'song', position: 'after' }] },
  { id: 'L-010', level: 10, answer: 'light', accepted: [],
    difficulty: 1, category: 'category.element',
    words: [{ text: 'day', position: 'before' }, { text: 'house', position: 'after' }, { text: 'moon', position: 'before' }] },
  { id: 'L-011', level: 11, answer: 'fire', accepted: [],
    difficulty: 2, category: 'category.element',
    words: [{ text: 'camp', position: 'before' }, { text: 'works', position: 'after' }, { text: 'place', position: 'after' }] },
  { id: 'L-012', level: 12, answer: 'cake', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'pan', position: 'before' }, { text: 'cup', position: 'before' }, { text: 'walk', position: 'after' }] },
  { id: 'L-013', level: 13, answer: 'friend', accepted: [],
    difficulty: 2, category: 'category.people',
    words: [{ text: 'boy', position: 'before' }, { text: 'girl', position: 'before' }, { text: 'ship', position: 'after' }] },
  { id: 'L-014', level: 14, answer: 'fish', accepted: [],
    difficulty: 2, category: 'category.animals',
    words: [{ text: 'cat', position: 'before' }, { text: 'bowl', position: 'after' }, { text: 'gold', position: 'before' }] },
  { id: 'L-015', level: 15, answer: 'man', accepted: [],
    difficulty: 2, category: 'category.people',
    words: [{ text: 'snow', position: 'before' }, { text: 'kind', position: 'after' }, { text: 'post', position: 'before' }] },
  { id: 'L-016', level: 16, answer: 'ground', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'back', position: 'before' }, { text: 'under', position: 'before' }, { text: 'work', position: 'after' }] },
  { id: 'L-017', level: 17, answer: 'foot', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'ball', position: 'after' }, { text: 'print', position: 'after' }, { text: 'bare', position: 'before' }] },
  { id: 'L-018', level: 18, answer: 'box', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'mail', position: 'before' }, { text: 'car', position: 'after' }, { text: 'sand', position: 'before' }] },
  { id: 'L-019', level: 19, answer: 'road', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'rail', position: 'before' }, { text: 'side', position: 'after' }, { text: 'block', position: 'after' }] },
  { id: 'L-020', level: 20, answer: 'head', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'ache', position: 'after' }, { text: 'light', position: 'after' }, { text: 'over', position: 'before' }] },
  { id: 'L-021', level: 21, answer: 'snow', accepted: [],
    difficulty: 2, category: 'category.weather',
    words: [{ text: 'ball', position: 'after' }, { text: 'flake', position: 'after' }, { text: 'man', position: 'after' }] },
  { id: 'L-022', level: 22, answer: 'board', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'card', position: 'before' }, { text: 'walk', position: 'after' }, { text: 'key', position: 'before' }] },
  { id: 'L-023', level: 23, answer: 'air', accepted: [],
    difficulty: 3, category: 'category.element',
    words: [{ text: 'port', position: 'after' }, { text: 'plane', position: 'after' }, { text: 'mid', position: 'before' }] },
  { id: 'L-024', level: 24, answer: 'star', accepted: [],
    difficulty: 2, category: 'category.sky',
    words: [{ text: 'fish', position: 'after' }, { text: 'light', position: 'after' }, { text: 'super', position: 'before' }] },
  { id: 'L-025', level: 25, answer: 'milk', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'shake', position: 'after' }, { text: 'butter', position: 'before' }, { text: 'man', position: 'after' }] },
  { id: 'L-026', level: 26, answer: 'back', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'draw', position: 'before' }, { text: 'ground', position: 'after' }, { text: 'pack', position: 'after' }] },
  { id: 'L-027', level: 27, answer: 'stone', accepted: [],
    difficulty: 2, category: 'category.material',
    words: [{ text: 'lime', position: 'before' }, { text: 'wall', position: 'after' }, { text: 'corner', position: 'before' }] },
  { id: 'L-028', level: 28, answer: 'card', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'board', position: 'after' }, { text: 'post', position: 'before' }, { text: 'wild', position: 'before' }] },
  { id: 'L-029', level: 29, answer: 'case', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'brief', position: 'before' }, { text: 'suit', position: 'before' }, { text: 'work', position: 'after' }] },
  { id: 'L-030', level: 30, answer: 'room', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'bath', position: 'before' }, { text: 'mate', position: 'after' }, { text: 'bed', position: 'before' }] },
  { id: 'L-031', level: 31, answer: 'game', accepted: [],
    difficulty: 3, category: 'category.play',
    words: [{ text: 'board', position: 'before' }, { text: 'show', position: 'after' }, { text: 'keeper', position: 'after' }] },
  { id: 'L-032', level: 32, answer: 'fall', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'water', position: 'before' }, { text: 'rain', position: 'before' }, { text: 'out', position: 'after' }] },
  { id: 'L-033', level: 33, answer: 'way', accepted: [],
    difficulty: 3, category: 'category.places',
    words: [{ text: 'high', position: 'before' }, { text: 'side', position: 'after' }, { text: 'gate', position: 'before' }] },
  { id: 'L-034', level: 34, answer: 'house', accepted: [],
    difficulty: 3, category: 'category.home',
    words: [{ text: 'green', position: 'before' }, { text: 'boat', position: 'after' }, { text: 'light', position: 'before' }] },
  { id: 'L-035', level: 35, answer: 'sun', accepted: [],
    difficulty: 3, category: 'category.sky',
    words: [{ text: 'flower', position: 'after' }, { text: 'shine', position: 'after' }, { text: 'rise', position: 'after' }] },
  { id: 'L-036', level: 36, answer: 'over', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'coat', position: 'after' }, { text: 'head', position: 'after' }, { text: 'left', position: 'before' }] },
  { id: 'L-037', level: 37, answer: 'word', accepted: [],
    difficulty: 4, category: 'category.things',
    words: [{ text: 'cross', position: 'before' }, { text: 'pass', position: 'before' }, { text: 'play', position: 'after' }] },
  { id: 'L-038', level: 38, answer: 'water', accepted: [],
    difficulty: 3, category: 'category.element',
    words: [{ text: 'fall', position: 'after' }, { text: 'melon', position: 'after' }, { text: 'under', position: 'before' }] },
  { id: 'L-039', level: 39, answer: 'out', accepted: [],
    difficulty: 3, category: 'category.places',
    words: [{ text: 'side', position: 'after' }, { text: 'break', position: 'after' }, { text: 'black', position: 'before' }] },
  { id: 'L-040', level: 40, answer: 'rain', accepted: [],
    difficulty: 3, category: 'category.weather',
    words: [{ text: 'bow', position: 'after' }, { text: 'coat', position: 'after' }, { text: 'drop', position: 'after' }] },
  { id: 'L-041', level: 41, answer: 'land', accepted: [],
    difficulty: 5, category: 'category.places',
    words: [{ text: 'main', position: 'before' }, { text: 'mark', position: 'after' }, { text: 'wood', position: 'before' }] },
  { id: 'L-042', level: 42, answer: 'eye', accepted: [],
    difficulty: 4, category: 'category.body',
    words: [{ text: 'ball', position: 'after' }, { text: 'brow', position: 'after' }, { text: 'bulls', position: 'before' }] },
  { id: 'L-043', level: 43, answer: 'night', accepted: [],
    difficulty: 3, category: 'category.time',
    words: [{ text: 'mare', position: 'after' }, { text: 'mid', position: 'before' }, { text: 'fall', position: 'after' }] },
  { id: 'L-044', level: 44, answer: 'sea', accepted: [],
    difficulty: 4, category: 'category.nature',
    words: [{ text: 'food', position: 'after' }, { text: 'shore', position: 'after' }, { text: 'side', position: 'after' }] },
  { id: 'L-045', level: 45, answer: 'key', accepted: [],
    difficulty: 5, category: 'category.things',
    words: [{ text: 'board', position: 'after' }, { text: 'hole', position: 'after' }, { text: 'turn', position: 'before' }] },
  { id: 'L-046', level: 46, answer: 'cup', accepted: [],
    difficulty: 5, category: 'category.home',
    words: [{ text: 'cake', position: 'after' }, { text: 'tea', position: 'before' }, { text: 'board', position: 'after' }] },
  { id: 'L-047', level: 47, answer: 'wood', accepted: [],
    difficulty: 4, category: 'category.material',
    words: [{ text: 'fire', position: 'before' }, { text: 'work', position: 'after' }, { text: 'land', position: 'after' }] },
  { id: 'L-048', level: 48, answer: 'hand', accepted: [],
    difficulty: 4, category: 'category.body',
    words: [{ text: 'bag', position: 'after' }, { text: 'shake', position: 'after' }, { text: 'second', position: 'before' }] },
  { id: 'L-049', level: 49, answer: 'watch', accepted: [],
    difficulty: 5, category: 'category.things',
    words: [{ text: 'wrist', position: 'before' }, { text: 'dog', position: 'after' }, { text: 'stop', position: 'before' }] },
  { id: 'L-050', level: 50, answer: 'down', accepted: [],
    difficulty: 5, category: 'category.time',
    words: [{ text: 'count', position: 'before' }, { text: 'stairs', position: 'after' }, { text: 'town', position: 'after' }] },
];
