import type { Level } from '@/lib/levels';

/**
 * ── THE LEVEL BANK — GENERATED, DO NOT EDIT ───────────────────────────────
 *
 * Written by `node scripts/build-levels.mjs` from `scripts/levels.source.mjs`.
 * Edit the source and re-run; edits here are lost on the next build.
 *
 * 100 levels. `level` is 1-based and permanent: it is the number
 * on the map, the key progress is stored under, and the thing a player says out
 * loud ("I'm on 34"). **Append only.** Inserting a level in the middle
 * renumbers every level after it and rewrites the history of everyone playing.
 *
 * Difficulty is derived, never hand-written — PRD §3.2. See the builder for
 * the heuristic and its limits, and run `scripts/puzzle-check.mjs` for the
 * two things no heuristic can decide: uniqueness and real corpus frequency.
 */
export const LEVELS: Level[] = [
  { id: 'L-001', level: 1, answer: 'brush', accepted: [],
    difficulty: 1, category: 'category.home',
    words: [{ text: 'tooth', position: 'before' }, { text: 'hair', position: 'before' }, { text: 'paint', position: 'before' }] },
  { id: 'L-002', level: 2, answer: 'ball', accepted: [],
    difficulty: 1, category: 'category.play',
    words: [{ text: 'foot', position: 'before' }, { text: 'room', position: 'after' }, { text: 'snow', position: 'before' }] },
  { id: 'L-003', level: 3, answer: 'door', accepted: [],
    difficulty: 1, category: 'category.home',
    words: [{ text: 'bell', position: 'after' }, { text: 'way', position: 'after' }, { text: 'out', position: 'before' }] },
  { id: 'L-004', level: 4, answer: 'camp', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'fire', position: 'after' }, { text: 'ground', position: 'after' }, { text: 'site', position: 'after' }] },
  { id: 'L-005', level: 5, answer: 'line', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'life', position: 'before' }, { text: 'on', position: 'before' }, { text: 'up', position: 'after' }] },
  { id: 'L-006', level: 6, answer: 'light', accepted: [],
    difficulty: 1, category: 'category.element',
    words: [{ text: 'day', position: 'before' }, { text: 'house', position: 'after' }, { text: 'moon', position: 'before' }] },
  { id: 'L-007', level: 7, answer: 'court', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'yard', position: 'after' }, { text: 'house', position: 'after' }, { text: 'room', position: 'after' }] },
  { id: 'L-008', level: 8, answer: 'rail', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'road', position: 'after' }, { text: 'way', position: 'after' }, { text: 'hand', position: 'before' }] },
  { id: 'L-009', level: 9, answer: 'side', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'walk', position: 'after' }, { text: 'out', position: 'before' }, { text: 'road', position: 'before' }] },
  { id: 'L-010', level: 10, answer: 'paint', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'brush', position: 'after' }, { text: 'ball', position: 'after' }, { text: 'work', position: 'after' }] },
  { id: 'L-011', level: 11, answer: 'bell', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'blue', position: 'before' }, { text: 'boy', position: 'after' }, { text: 'door', position: 'before' }] },
  { id: 'L-012', level: 12, answer: 'time', accepted: [],
    difficulty: 1, category: 'category.time',
    words: [{ text: 'table', position: 'after' }, { text: 'some', position: 'before' }, { text: 'life', position: 'before' }] },
  { id: 'L-013', level: 13, answer: 'cake', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'pan', position: 'before' }, { text: 'cup', position: 'before' }, { text: 'walk', position: 'after' }] },
  { id: 'L-014', level: 14, answer: 'book', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'case', position: 'after' }, { text: 'note', position: 'before' }, { text: 'mark', position: 'after' }] },
  { id: 'L-015', level: 15, answer: 'farm', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'house', position: 'after' }, { text: 'yard', position: 'after' }, { text: 'land', position: 'after' }] },
  { id: 'L-016', level: 16, answer: 'corn', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'pop', position: 'before' }, { text: 'bread', position: 'after' }, { text: 'field', position: 'after' }] },
  { id: 'L-017', level: 17, answer: 'boy', accepted: [],
    difficulty: 2, category: 'category.people',
    words: [{ text: 'cow', position: 'before' }, { text: 'friend', position: 'after' }, { text: 'bell', position: 'before' }] },
  { id: 'L-018', level: 18, answer: 'head', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'ache', position: 'after' }, { text: 'light', position: 'after' }, { text: 'over', position: 'before' }] },
  { id: 'L-019', level: 19, answer: 'fire', accepted: [],
    difficulty: 2, category: 'category.element',
    words: [{ text: 'camp', position: 'before' }, { text: 'works', position: 'after' }, { text: 'place', position: 'after' }] },
  { id: 'L-020', level: 20, answer: 'paper', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'news', position: 'before' }, { text: 'back', position: 'after' }, { text: 'wall', position: 'before' }] },
  { id: 'L-021', level: 21, answer: 'hair', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'cut', position: 'after' }, { text: 'brush', position: 'after' }, { text: 'style', position: 'after' }] },
  { id: 'L-022', level: 22, answer: 'shot', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'screen', position: 'before' }, { text: 'gun', position: 'after' }, { text: 'snap', position: 'before' }] },
  { id: 'L-023', level: 23, answer: 'mark', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'book', position: 'before' }, { text: 'land', position: 'before' }, { text: 'trade', position: 'before' }] },
  { id: 'L-024', level: 24, answer: 'field', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'corn', position: 'before' }, { text: 'work', position: 'after' }, { text: 'battle', position: 'before' }] },
  { id: 'L-025', level: 25, answer: 'cow', accepted: [],
    difficulty: 2, category: 'category.animals',
    words: [{ text: 'boy', position: 'after' }, { text: 'girl', position: 'after' }, { text: 'hide', position: 'after' }] },
  { id: 'L-026', level: 26, answer: 'mill', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'wind', position: 'before' }, { text: 'stone', position: 'after' }, { text: 'saw', position: 'before' }] },
  { id: 'L-027', level: 27, answer: 'letter', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'news', position: 'before' }, { text: 'box', position: 'after' }, { text: 'head', position: 'after' }] },
  { id: 'L-028', level: 28, answer: 'road', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'rail', position: 'before' }, { text: 'side', position: 'after' }, { text: 'block', position: 'after' }] },
  { id: 'L-029', level: 29, answer: 'room', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'bath', position: 'before' }, { text: 'mate', position: 'after' }, { text: 'bed', position: 'before' }] },
  { id: 'L-030', level: 30, answer: 'walk', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'side', position: 'before' }, { text: 'way', position: 'after' }, { text: 'board', position: 'before' }] },
  { id: 'L-031', level: 31, answer: 'site', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'camp', position: 'before' }, { text: 'web', position: 'before' }, { text: 'work', position: 'before' }] },
  { id: 'L-032', level: 32, answer: 'gun', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'shot', position: 'after' }, { text: 'fire', position: 'after' }, { text: 'powder', position: 'after' }] },
  { id: 'L-033', level: 33, answer: 'trade', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'mark', position: 'after' }, { text: 'off', position: 'after' }, { text: 'man', position: 'after' }] },
  { id: 'L-034', level: 34, answer: 'snow', accepted: [],
    difficulty: 2, category: 'category.weather',
    words: [{ text: 'ball', position: 'after' }, { text: 'flake', position: 'after' }, { text: 'man', position: 'after' }] },
  { id: 'L-035', level: 35, answer: 'work', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'home', position: 'before' }, { text: 'shop', position: 'after' }, { text: 'net', position: 'before' }] },
  { id: 'L-036', level: 36, answer: 'news', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'paper', position: 'after' }, { text: 'cast', position: 'after' }, { text: 'letter', position: 'after' }] },
  { id: 'L-037', level: 37, answer: 'star', accepted: [],
    difficulty: 2, category: 'category.sky',
    words: [{ text: 'fish', position: 'after' }, { text: 'light', position: 'after' }, { text: 'super', position: 'before' }] },
  { id: 'L-038', level: 38, answer: 'back', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'draw', position: 'before' }, { text: 'ground', position: 'after' }, { text: 'pack', position: 'after' }] },
  { id: 'L-039', level: 39, answer: 'bath', accepted: [],
    difficulty: 3, category: 'category.home',
    words: [{ text: 'room', position: 'after' }, { text: 'tub', position: 'after' }, { text: 'blood', position: 'before' }] },
  { id: 'L-040', level: 40, answer: 'wind', accepted: [],
    difficulty: 2, category: 'category.weather',
    words: [{ text: 'mill', position: 'after' }, { text: 'screen', position: 'after' }, { text: 'whirl', position: 'before' }] },
  { id: 'L-041', level: 41, answer: 'bird', accepted: [],
    difficulty: 3, category: 'category.animals',
    words: [{ text: 'black', position: 'before' }, { text: 'house', position: 'after' }, { text: 'song', position: 'after' }] },
  { id: 'L-042', level: 42, answer: 'bed', accepted: [],
    difficulty: 3, category: 'category.home',
    words: [{ text: 'room', position: 'after' }, { text: 'time', position: 'after' }, { text: 'flower', position: 'before' }] },
  { id: 'L-043', level: 43, answer: 'case', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'brief', position: 'before' }, { text: 'suit', position: 'before' }, { text: 'work', position: 'after' }] },
  { id: 'L-044', level: 44, answer: 'board', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'card', position: 'before' }, { text: 'walk', position: 'after' }, { text: 'key', position: 'before' }] },
  { id: 'L-045', level: 45, answer: 'fish', accepted: [],
    difficulty: 3, category: 'category.animals',
    words: [{ text: 'cat', position: 'before' }, { text: 'bowl', position: 'after' }, { text: 'gold', position: 'before' }] },
  { id: 'L-046', level: 46, answer: 'ground', accepted: [],
    difficulty: 3, category: 'category.places',
    words: [{ text: 'back', position: 'before' }, { text: 'under', position: 'before' }, { text: 'work', position: 'after' }] },
  { id: 'L-047', level: 47, answer: 'bread', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'corn', position: 'before' }, { text: 'crumb', position: 'after' }, { text: 'winner', position: 'after' }] },
  { id: 'L-048', level: 48, answer: 'foot', accepted: [],
    difficulty: 3, category: 'category.body',
    words: [{ text: 'ball', position: 'after' }, { text: 'print', position: 'after' }, { text: 'bare', position: 'before' }] },
  { id: 'L-049', level: 49, answer: 'friend', accepted: [],
    difficulty: 3, category: 'category.people',
    words: [{ text: 'boy', position: 'before' }, { text: 'girl', position: 'before' }, { text: 'ship', position: 'after' }] },
  { id: 'L-050', level: 50, answer: 'fall', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'water', position: 'before' }, { text: 'rain', position: 'before' }, { text: 'out', position: 'after' }] },
  { id: 'L-051', level: 51, answer: 'cat', accepted: [],
    difficulty: 3, category: 'category.animals',
    words: [{ text: 'fish', position: 'after' }, { text: 'walk', position: 'after' }, { text: 'bob', position: 'before' }] },
  { id: 'L-052', level: 52, answer: 'game', accepted: [],
    difficulty: 3, category: 'category.play',
    words: [{ text: 'board', position: 'before' }, { text: 'show', position: 'after' }, { text: 'keeper', position: 'after' }] },
  { id: 'L-053', level: 53, answer: 'milk', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'shake', position: 'after' }, { text: 'butter', position: 'before' }, { text: 'man', position: 'after' }] },
  { id: 'L-054', level: 54, answer: 'house', accepted: [],
    difficulty: 3, category: 'category.home',
    words: [{ text: 'green', position: 'before' }, { text: 'boat', position: 'after' }, { text: 'light', position: 'before' }] },
  { id: 'L-055', level: 55, answer: 'over', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'coat', position: 'after' }, { text: 'head', position: 'after' }, { text: 'left', position: 'before' }] },
  { id: 'L-056', level: 56, answer: 'moon', accepted: [],
    difficulty: 3, category: 'category.sky',
    words: [{ text: 'light', position: 'after' }, { text: 'honey', position: 'before' }, { text: 'beam', position: 'after' }] },
  { id: 'L-057', level: 57, answer: 'man', accepted: [],
    difficulty: 3, category: 'category.people',
    words: [{ text: 'snow', position: 'before' }, { text: 'kind', position: 'after' }, { text: 'post', position: 'before' }] },
  { id: 'L-058', level: 58, answer: 'pea', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'nut', position: 'after' }, { text: 'cock', position: 'after' }, { text: 'shooter', position: 'after' }] },
  { id: 'L-059', level: 59, answer: 'rain', accepted: [],
    difficulty: 3, category: 'category.weather',
    words: [{ text: 'bow', position: 'after' }, { text: 'coat', position: 'after' }, { text: 'drop', position: 'after' }] },
  { id: 'L-060', level: 60, answer: 'net', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'work', position: 'after' }, { text: 'ball', position: 'after' }, { text: 'inter', position: 'before' }] },
  { id: 'L-061', level: 61, answer: 'sheep', accepted: [],
    difficulty: 3, category: 'category.animals',
    words: [{ text: 'dog', position: 'after' }, { text: 'skin', position: 'after' }, { text: 'fold', position: 'after' }] },
  { id: 'L-062', level: 62, answer: 'screen', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'wind', position: 'before' }, { text: 'play', position: 'after' }, { text: 'shot', position: 'after' }] },
  { id: 'L-063', level: 63, answer: 'yard', accepted: [],
    difficulty: 3, category: 'category.places',
    words: [{ text: 'ship', position: 'before' }, { text: 'court', position: 'before' }, { text: 'stick', position: 'after' }] },
  { id: 'L-064', level: 64, answer: 'ship', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'friend', position: 'before' }, { text: 'yard', position: 'after' }, { text: 'war', position: 'before' }] },
  { id: 'L-065', level: 65, answer: 'chair', accepted: [],
    difficulty: 4, category: 'category.home',
    words: [{ text: 'arm', position: 'before' }, { text: 'wheel', position: 'before' }, { text: 'man', position: 'after' }] },
  { id: 'L-066', level: 66, answer: 'box', accepted: [],
    difficulty: 4, category: 'category.things',
    words: [{ text: 'mail', position: 'before' }, { text: 'car', position: 'after' }, { text: 'sand', position: 'before' }] },
  { id: 'L-067', level: 67, answer: 'tooth', accepted: [],
    difficulty: 3, category: 'category.body',
    words: [{ text: 'brush', position: 'after' }, { text: 'ache', position: 'after' }, { text: 'paste', position: 'after' }] },
  { id: 'L-068', level: 68, answer: 'dog', accepted: [],
    difficulty: 4, category: 'category.animals',
    words: [{ text: 'watch', position: 'before' }, { text: 'house', position: 'after' }, { text: 'hot', position: 'before' }] },
  { id: 'L-069', level: 69, answer: 'egg', accepted: [],
    difficulty: 4, category: 'category.food',
    words: [{ text: 'shell', position: 'after' }, { text: 'plant', position: 'after' }, { text: 'nog', position: 'after' }] },
  { id: 'L-070', level: 70, answer: 'card', accepted: [],
    difficulty: 4, category: 'category.things',
    words: [{ text: 'board', position: 'after' }, { text: 'post', position: 'before' }, { text: 'wild', position: 'before' }] },
  { id: 'L-071', level: 71, answer: 'hand', accepted: [],
    difficulty: 4, category: 'category.body',
    words: [{ text: 'bag', position: 'after' }, { text: 'shake', position: 'after' }, { text: 'second', position: 'before' }] },
  { id: 'L-072', level: 72, answer: 'eye', accepted: [],
    difficulty: 4, category: 'category.body',
    words: [{ text: 'ball', position: 'after' }, { text: 'brow', position: 'after' }, { text: 'bulls', position: 'before' }] },
  { id: 'L-073', level: 73, answer: 'out', accepted: [],
    difficulty: 4, category: 'category.places',
    words: [{ text: 'side', position: 'after' }, { text: 'break', position: 'after' }, { text: 'black', position: 'before' }] },
  { id: 'L-074', level: 74, answer: 'night', accepted: [],
    difficulty: 4, category: 'category.time',
    words: [{ text: 'mare', position: 'after' }, { text: 'mid', position: 'before' }, { text: 'fall', position: 'after' }] },
  { id: 'L-075', level: 75, answer: 'shell', accepted: [],
    difficulty: 4, category: 'category.nature',
    words: [{ text: 'sea', position: 'before' }, { text: 'fish', position: 'after' }, { text: 'nut', position: 'before' }] },
  { id: 'L-076', level: 76, answer: 'pan', accepted: [],
    difficulty: 4, category: 'category.home',
    words: [{ text: 'cake', position: 'after' }, { text: 'sauce', position: 'before' }, { text: 'handle', position: 'after' }] },
  { id: 'L-077', level: 77, answer: 'water', accepted: [],
    difficulty: 4, category: 'category.element',
    words: [{ text: 'fall', position: 'after' }, { text: 'melon', position: 'after' }, { text: 'under', position: 'before' }] },
  { id: 'L-078', level: 78, answer: 'stone', accepted: [],
    difficulty: 4, category: 'category.material',
    words: [{ text: 'lime', position: 'before' }, { text: 'wall', position: 'after' }, { text: 'corner', position: 'before' }] },
  { id: 'L-079', level: 79, answer: 'sun', accepted: [],
    difficulty: 4, category: 'category.sky',
    words: [{ text: 'flower', position: 'after' }, { text: 'shine', position: 'after' }, { text: 'rise', position: 'after' }] },
  { id: 'L-080', level: 80, answer: 'pig', accepted: [],
    difficulty: 4, category: 'category.animals',
    words: [{ text: 'tail', position: 'after' }, { text: 'pen', position: 'after' }, { text: 'skin', position: 'after' }] },
  { id: 'L-081', level: 81, answer: 'way', accepted: [],
    difficulty: 4, category: 'category.places',
    words: [{ text: 'high', position: 'before' }, { text: 'side', position: 'after' }, { text: 'gate', position: 'before' }] },
  { id: 'L-082', level: 82, answer: 'nut', accepted: [],
    difficulty: 4, category: 'category.food',
    words: [{ text: 'shell', position: 'after' }, { text: 'pea', position: 'before' }, { text: 'coco', position: 'before' }] },
  { id: 'L-083', level: 83, answer: 'air', accepted: [],
    difficulty: 5, category: 'category.element',
    words: [{ text: 'port', position: 'after' }, { text: 'plane', position: 'after' }, { text: 'mid', position: 'before' }] },
  { id: 'L-084', level: 84, answer: 'wood', accepted: [],
    difficulty: 4, category: 'category.material',
    words: [{ text: 'fire', position: 'before' }, { text: 'work', position: 'after' }, { text: 'land', position: 'after' }] },
  { id: 'L-085', level: 85, answer: 'bug', accepted: [],
    difficulty: 5, category: 'category.animals',
    words: [{ text: 'lady', position: 'before' }, { text: 'fire', position: 'before' }, { text: 'bear', position: 'after' }] },
  { id: 'L-086', level: 86, answer: 'battle', accepted: [],
    difficulty: 5, category: 'category.things',
    words: [{ text: 'field', position: 'after' }, { text: 'ship', position: 'after' }, { text: 'axe', position: 'after' }] },
  { id: 'L-087', level: 87, answer: 'word', accepted: [],
    difficulty: 4, category: 'category.things',
    words: [{ text: 'cross', position: 'before' }, { text: 'pass', position: 'before' }, { text: 'play', position: 'after' }] },
  { id: 'L-088', level: 88, answer: 'butter', accepted: [],
    difficulty: 5, category: 'category.food',
    words: [{ text: 'milk', position: 'after' }, { text: 'fly', position: 'after' }, { text: 'cup', position: 'after' }] },
  { id: 'L-089', level: 89, answer: 'horse', accepted: [],
    difficulty: 5, category: 'category.animals',
    words: [{ text: 'sea', position: 'before' }, { text: 'shoe', position: 'after' }, { text: 'race', position: 'before' }] },
  { id: 'L-090', level: 90, answer: 'berry', accepted: [],
    difficulty: 5, category: 'category.food',
    words: [{ text: 'blue', position: 'before' }, { text: 'straw', position: 'before' }, { text: 'black', position: 'before' }] },
  { id: 'L-091', level: 91, answer: 'pot', accepted: [],
    difficulty: 5, category: 'category.home',
    words: [{ text: 'tea', position: 'before' }, { text: 'hole', position: 'after' }, { text: 'jack', position: 'before' }] },
  { id: 'L-092', level: 92, answer: 'down', accepted: [],
    difficulty: 5, category: 'category.time',
    words: [{ text: 'count', position: 'before' }, { text: 'stairs', position: 'after' }, { text: 'town', position: 'after' }] },
  { id: 'L-093', level: 93, answer: 'land', accepted: [],
    difficulty: 5, category: 'category.places',
    words: [{ text: 'main', position: 'before' }, { text: 'mark', position: 'after' }, { text: 'wood', position: 'before' }] },
  { id: 'L-094', level: 94, answer: 'cup', accepted: [],
    difficulty: 5, category: 'category.home',
    words: [{ text: 'cake', position: 'after' }, { text: 'tea', position: 'before' }, { text: 'board', position: 'after' }] },
  { id: 'L-095', level: 95, answer: 'stick', accepted: [],
    difficulty: 5, category: 'category.things',
    words: [{ text: 'yard', position: 'before' }, { text: 'chop', position: 'before' }, { text: 'lip', position: 'before' }] },
  { id: 'L-096', level: 96, answer: 'fly', accepted: [],
    difficulty: 5, category: 'category.animals',
    words: [{ text: 'butter', position: 'before' }, { text: 'paper', position: 'after' }, { text: 'dragon', position: 'before' }] },
  { id: 'L-097', level: 97, answer: 'key', accepted: [],
    difficulty: 5, category: 'category.things',
    words: [{ text: 'board', position: 'after' }, { text: 'hole', position: 'after' }, { text: 'turn', position: 'before' }] },
  { id: 'L-098', level: 98, answer: 'under', accepted: [],
    difficulty: 5, category: 'category.places',
    words: [{ text: 'stand', position: 'after' }, { text: 'ground', position: 'after' }, { text: 'wear', position: 'after' }] },
  { id: 'L-099', level: 99, answer: 'watch', accepted: [],
    difficulty: 5, category: 'category.things',
    words: [{ text: 'wrist', position: 'before' }, { text: 'dog', position: 'after' }, { text: 'stop', position: 'before' }] },
  { id: 'L-100', level: 100, answer: 'sea', accepted: [],
    difficulty: 5, category: 'category.nature',
    words: [{ text: 'food', position: 'after' }, { text: 'shore', position: 'after' }, { text: 'side', position: 'after' }] },
];
