import type { Level } from '@/lib/levels';

/**
 * ── THE PACK LEVELS — GENERATED, DO NOT EDIT ──────────────────────────
 *
 * Written by `node scripts/build-levels.mjs` from `scripts/levels.source.mjs`.
 * Edit the source and re-run; edits here are lost on the next build.
 *
 * 250 levels. `level` is 1-based within its own bank and permanent: it is
 * the number on the map, the key progress is stored under, and the thing a
 * player says out loud. **Append only.** Inserting a level renumbers every one
 * after it and rewrites the history of everyone playing.
 *
 * Difficulty is derived, never hand-written — PRD §3.2. Run
 * `scripts/puzzle-check.mjs` for the two things no heuristic can decide:
 * uniqueness and real corpus frequency.
 *
 * **These share nothing with the free run.** Every answer appears in exactly
 * one bank. That was the session-7 bug — packs pointed at levels 21–100 of
 * the free bank, so buying one bought puzzles you had already played.
 */
export const PACK_LEVELS: Record<string, Level[]> = {
  'kitchen': [
  { id: 'KI-001', level: 1, answer: 'cloth', accepted: [],
    difficulty: 1, category: 'category.home',
    words: [{ text: 'dish', position: 'before' }, { text: 'table', position: 'before' }, { text: 'wash', position: 'before' }] },
  { id: 'KI-002', level: 2, answer: 'apple', accepted: [],
    difficulty: 1, category: 'category.food',
    words: [{ text: 'pine', position: 'before' }, { text: 'sauce', position: 'after' }, { text: 'cart', position: 'after' }] },
  { id: 'KI-003', level: 3, answer: 'lunch', accepted: [],
    difficulty: 1, category: 'category.food',
    words: [{ text: 'box', position: 'after' }, { text: 'time', position: 'after' }, { text: 'room', position: 'after' }] },
  { id: 'KI-004', level: 4, answer: 'corn', accepted: [],
    difficulty: 1, category: 'category.food',
    words: [{ text: 'pop', position: 'before' }, { text: 'bread', position: 'after' }, { text: 'field', position: 'after' }] },
  { id: 'KI-005', level: 5, answer: 'table', accepted: [],
    difficulty: 1, category: 'category.home',
    words: [{ text: 'time', position: 'before' }, { text: 'cloth', position: 'after' }, { text: 'spoon', position: 'after' }] },
  { id: 'KI-006', level: 6, answer: 'pop', accepted: [],
    difficulty: 1, category: 'category.food',
    words: [{ text: 'corn', position: 'after' }, { text: 'gun', position: 'after' }, { text: 'up', position: 'after' }] },
  { id: 'KI-007', level: 7, answer: 'jelly', accepted: [],
    difficulty: 1, category: 'category.food',
    words: [{ text: 'fish', position: 'after' }, { text: 'bean', position: 'after' }, { text: 'roll', position: 'after' }] },
  { id: 'KI-008', level: 8, answer: 'bake', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'house', position: 'after' }, { text: 'ware', position: 'after' }, { text: 'off', position: 'after' }] },
  { id: 'KI-009', level: 9, answer: 'butter', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'milk', position: 'after' }, { text: 'fly', position: 'after' }, { text: 'cup', position: 'after' }] },
  { id: 'KI-010', level: 10, answer: 'sweet', accepted: [],
    difficulty: 1, category: 'category.food',
    words: [{ text: 'meat', position: 'after' }, { text: 'heart', position: 'after' }, { text: 'corn', position: 'after' }] },
  { id: 'KI-011', level: 11, answer: 'dish', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'cloth', position: 'after' }, { text: 'washer', position: 'after' }, { text: 'rag', position: 'after' }] },
  { id: 'KI-012', level: 12, answer: 'cook', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'book', position: 'after' }, { text: 'ware', position: 'after' }, { text: 'house', position: 'after' }] },
  { id: 'KI-013', level: 13, answer: 'ginger', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'bread', position: 'after' }, { text: 'snap', position: 'after' }, { text: 'root', position: 'after' }] },
  { id: 'KI-014', level: 14, answer: 'dough', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'nut', position: 'after' }, { text: 'sour', position: 'before' }, { text: 'boy', position: 'after' }] },
  { id: 'KI-015', level: 15, answer: 'knife', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'pen', position: 'before' }, { text: 'jack', position: 'before' }, { text: 'point', position: 'after' }] },
  { id: 'KI-016', level: 16, answer: 'grape', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'fruit', position: 'after' }, { text: 'vine', position: 'after' }, { text: 'shot', position: 'after' }] },
  { id: 'KI-017', level: 17, answer: 'salt', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'water', position: 'after' }, { text: 'shaker', position: 'after' }, { text: 'cellar', position: 'after' }] },
  { id: 'KI-018', level: 18, answer: 'lime', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'stone', position: 'after' }, { text: 'light', position: 'after' }, { text: 'sub', position: 'before' }] },
  { id: 'KI-019', level: 19, answer: 'meat', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'ball', position: 'after' }, { text: 'loaf', position: 'after' }, { text: 'sweet', position: 'before' }] },
  { id: 'KI-020', level: 20, answer: 'honey', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'moon', position: 'after' }, { text: 'comb', position: 'after' }, { text: 'bee', position: 'after' }] },
  { id: 'KI-021', level: 21, answer: 'sauce', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'pan', position: 'after' }, { text: 'apple', position: 'before' }, { text: 'boat', position: 'after' }] },
  { id: 'KI-022', level: 22, answer: 'fruit', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'grape', position: 'before' }, { text: 'cake', position: 'after' }, { text: 'ful', position: 'after' }] },
  { id: 'KI-023', level: 23, answer: 'spoon', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'tea', position: 'before' }, { text: 'table', position: 'before' }, { text: 'full', position: 'after' }] },
  { id: 'KI-024', level: 24, answer: 'seed', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'pod', position: 'after' }, { text: 'bird', position: 'before' }, { text: 'ling', position: 'after' }] },
  { id: 'KI-025', level: 25, answer: 'wash', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'cloth', position: 'after' }, { text: 'basin', position: 'after' }, { text: 'room', position: 'after' }] },
  { id: 'KI-026', level: 26, answer: 'straw', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'berry', position: 'after' }, { text: 'man', position: 'after' }, { text: 'board', position: 'after' }] },
  { id: 'KI-027', level: 27, answer: 'soap', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'box', position: 'after' }, { text: 'suds', position: 'after' }, { text: 'stone', position: 'after' }] },
  { id: 'KI-028', level: 28, answer: 'bean', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'jelly', position: 'before' }, { text: 'stalk', position: 'after' }, { text: 'bag', position: 'after' }] },
  { id: 'KI-029', level: 29, answer: 'break', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'fast', position: 'after' }, { text: 'down', position: 'after' }, { text: 'out', position: 'before' }] },
  { id: 'KI-030', level: 30, answer: 'tea', accepted: [],
    difficulty: 2, category: 'category.food',
    words: [{ text: 'pot', position: 'after' }, { text: 'cup', position: 'after' }, { text: 'spoon', position: 'after' }] },
  { id: 'KI-031', level: 31, answer: 'bread', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'corn', position: 'before' }, { text: 'crumb', position: 'after' }, { text: 'winner', position: 'after' }] },
  { id: 'KI-032', level: 32, answer: 'bowl', accepted: [],
    difficulty: 3, category: 'category.home',
    words: [{ text: 'fish', position: 'before' }, { text: 'super', position: 'before' }, { text: 'ful', position: 'after' }] },
  { id: 'KI-033', level: 33, answer: 'cob', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'corn', position: 'before' }, { text: 'web', position: 'after' }, { text: 'nut', position: 'after' }] },
  { id: 'KI-034', level: 34, answer: 'berry', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'blue', position: 'before' }, { text: 'straw', position: 'before' }, { text: 'black', position: 'before' }] },
  { id: 'KI-035', level: 35, answer: 'pan', accepted: [],
    difficulty: 3, category: 'category.home',
    words: [{ text: 'cake', position: 'after' }, { text: 'sauce', position: 'before' }, { text: 'handle', position: 'after' }] },
  { id: 'KI-036', level: 36, answer: 'fork', accepted: [],
    difficulty: 3, category: 'category.home',
    words: [{ text: 'pitch', position: 'before' }, { text: 'lift', position: 'after' }, { text: 'ful', position: 'after' }] },
  { id: 'KI-037', level: 37, answer: 'cheese', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'burger', position: 'after' }, { text: 'cake', position: 'after' }, { text: 'board', position: 'after' }] },
  { id: 'KI-038', level: 38, answer: 'pea', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'nut', position: 'after' }, { text: 'cock', position: 'after' }, { text: 'shooter', position: 'after' }] },
  { id: 'KI-039', level: 39, answer: 'pepper', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'mint', position: 'after' }, { text: 'corn', position: 'after' }, { text: 'box', position: 'after' }] },
  { id: 'KI-040', level: 40, answer: 'ice', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'berg', position: 'after' }, { text: 'box', position: 'after' }, { text: 'breaker', position: 'after' }] },
  { id: 'KI-041', level: 41, answer: 'wheat', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'buck', position: 'before' }, { text: 'germ', position: 'after' }, { text: 'field', position: 'after' }] },
  { id: 'KI-042', level: 42, answer: 'plate', accepted: [],
    difficulty: 3, category: 'category.home',
    words: [{ text: 'name', position: 'before' }, { text: 'ful', position: 'after' }, { text: 'hot', position: 'before' }] },
  { id: 'KI-043', level: 43, answer: 'bar', accepted: [],
    difficulty: 4, category: 'category.home',
    words: [{ text: 'tender', position: 'after' }, { text: 'code', position: 'after' }, { text: 'crow', position: 'before' }] },
  { id: 'KI-044', level: 44, answer: 'roll', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'drum', position: 'before' }, { text: 'over', position: 'after' }, { text: 'coaster', position: 'after' }] },
  { id: 'KI-045', level: 45, answer: 'pot', accepted: [],
    difficulty: 4, category: 'category.home',
    words: [{ text: 'tea', position: 'before' }, { text: 'hole', position: 'after' }, { text: 'jack', position: 'before' }] },
  { id: 'KI-046', level: 46, answer: 'egg', accepted: [],
    difficulty: 4, category: 'category.food',
    words: [{ text: 'shell', position: 'after' }, { text: 'plant', position: 'after' }, { text: 'nog', position: 'after' }] },
  { id: 'KI-047', level: 47, answer: 'pod', accepted: [],
    difficulty: 3, category: 'category.food',
    words: [{ text: 'pea', position: 'before' }, { text: 'cast', position: 'after' }, { text: 'seed', position: 'before' }] },
  { id: 'KI-048', level: 48, answer: 'sugar', accepted: [],
    difficulty: 4, category: 'category.food',
    words: [{ text: 'cane', position: 'after' }, { text: 'plum', position: 'after' }, { text: 'coat', position: 'after' }] },
  { id: 'KI-049', level: 49, answer: 'pie', accepted: [],
    difficulty: 5, category: 'category.food',
    words: [{ text: 'mag', position: 'before' }, { text: 'crust', position: 'after' }, { text: 'bald', position: 'after' }] },
  { id: 'KI-050', level: 50, answer: 'nut', accepted: [],
    difficulty: 4, category: 'category.food',
    words: [{ text: 'shell', position: 'after' }, { text: 'pea', position: 'before' }, { text: 'coco', position: 'before' }] },
  ],
  'outdoors': [
  { id: 'OU-001', level: 1, answer: 'camp', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'fire', position: 'after' }, { text: 'ground', position: 'after' }, { text: 'site', position: 'after' }] },
  { id: 'OU-002', level: 2, answer: 'bank', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'river', position: 'before' }, { text: 'note', position: 'after' }, { text: 'side', position: 'after' }] },
  { id: 'OU-003', level: 3, answer: 'sand', accepted: [],
    difficulty: 1, category: 'category.nature',
    words: [{ text: 'box', position: 'after' }, { text: 'storm', position: 'after' }, { text: 'paper', position: 'after' }] },
  { id: 'OU-004', level: 4, answer: 'field', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'corn', position: 'before' }, { text: 'work', position: 'after' }, { text: 'battle', position: 'before' }] },
  { id: 'OU-005', level: 5, answer: 'cave', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'man', position: 'after' }, { text: 'in', position: 'after' }, { text: 'dweller', position: 'after' }] },
  { id: 'OU-006', level: 6, answer: 'storm', accepted: [],
    difficulty: 1, category: 'category.weather',
    words: [{ text: 'brain', position: 'before' }, { text: 'cloud', position: 'after' }, { text: 'thunder', position: 'before' }] },
  { id: 'OU-007', level: 7, answer: 'river', accepted: [],
    difficulty: 1, category: 'category.nature',
    words: [{ text: 'bed', position: 'after' }, { text: 'bank', position: 'after' }, { text: 'side', position: 'after' }] },
  { id: 'OU-008', level: 8, answer: 'path', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'way', position: 'after' }, { text: 'foot', position: 'before' }, { text: 'tow', position: 'before' }] },
  { id: 'OU-009', level: 9, answer: 'earth', accepted: [],
    difficulty: 2, category: 'category.nature',
    words: [{ text: 'quake', position: 'after' }, { text: 'worm', position: 'after' }, { text: 'work', position: 'after' }] },
  { id: 'OU-010', level: 10, answer: 'week', accepted: [],
    difficulty: 1, category: 'category.time',
    words: [{ text: 'end', position: 'after' }, { text: 'day', position: 'after' }, { text: 'mid', position: 'before' }] },
  { id: 'OU-011', level: 11, answer: 'flower', accepted: [],
    difficulty: 2, category: 'category.nature',
    words: [{ text: 'sun', position: 'before' }, { text: 'pot', position: 'after' }, { text: 'bed', position: 'after' }] },
  { id: 'OU-012', level: 12, answer: 'farm', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'house', position: 'after' }, { text: 'yard', position: 'after' }, { text: 'land', position: 'after' }] },
  { id: 'OU-013', level: 13, answer: 'cloud', accepted: [],
    difficulty: 2, category: 'category.weather',
    words: [{ text: 'storm', position: 'before' }, { text: 'burst', position: 'after' }, { text: 'thunder', position: 'before' }] },
  { id: 'OU-014', level: 14, answer: 'hill', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'side', position: 'after' }, { text: 'top', position: 'after' }, { text: 'up', position: 'before' }] },
  { id: 'OU-015', level: 15, answer: 'summer', accepted: [],
    difficulty: 2, category: 'category.time',
    words: [{ text: 'time', position: 'after' }, { text: 'house', position: 'after' }, { text: 'mid', position: 'before' }] },
  { id: 'OU-016', level: 16, answer: 'pine', accepted: [],
    difficulty: 2, category: 'category.nature',
    words: [{ text: 'apple', position: 'after' }, { text: 'cone', position: 'after' }, { text: 'tree', position: 'after' }] },
  { id: 'OU-017', level: 17, answer: 'lake', accepted: [],
    difficulty: 2, category: 'category.nature',
    words: [{ text: 'side', position: 'after' }, { text: 'front', position: 'after' }, { text: 'bed', position: 'after' }] },
  { id: 'OU-018', level: 18, answer: 'track', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'race', position: 'before' }, { text: 'back', position: 'after' }, { text: 'side', position: 'after' }] },
  { id: 'OU-019', level: 19, answer: 'tree', accepted: [],
    difficulty: 2, category: 'category.nature',
    words: [{ text: 'top', position: 'after' }, { text: 'house', position: 'after' }, { text: 'line', position: 'after' }] },
  { id: 'OU-020', level: 20, answer: 'smoke', accepted: [],
    difficulty: 2, category: 'category.nature',
    words: [{ text: 'screen', position: 'after' }, { text: 'stack', position: 'after' }, { text: 'house', position: 'after' }] },
  { id: 'OU-021', level: 21, answer: 'day', accepted: [],
    difficulty: 3, category: 'category.time',
    words: [{ text: 'birth', position: 'before' }, { text: 'light', position: 'after' }, { text: 'break', position: 'after' }] },
  { id: 'OU-022', level: 22, answer: 'wind', accepted: [],
    difficulty: 2, category: 'category.weather',
    words: [{ text: 'mill', position: 'after' }, { text: 'screen', position: 'after' }, { text: 'whirl', position: 'before' }] },
  { id: 'OU-023', level: 23, answer: 'coast', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'line', position: 'after' }, { text: 'guard', position: 'after' }, { text: 'sea', position: 'before' }] },
  { id: 'OU-024', level: 24, answer: 'bridge', accepted: [],
    difficulty: 3, category: 'category.places',
    words: [{ text: 'draw', position: 'before' }, { text: 'foot', position: 'before' }, { text: 'head', position: 'after' }] },
  { id: 'OU-025', level: 25, answer: 'gate', accepted: [],
    difficulty: 3, category: 'category.places',
    words: [{ text: 'way', position: 'after' }, { text: 'flood', position: 'before' }, { text: 'keeper', position: 'after' }] },
  { id: 'OU-026', level: 26, answer: 'branch', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'out', position: 'after' }, { text: 'off', position: 'after' }, { text: 'tree', position: 'before' }] },
  { id: 'OU-027', level: 27, answer: 'brook', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'babbling', position: 'before' }, { text: 'side', position: 'after' }, { text: 'let', position: 'after' }] },
  { id: 'OU-028', level: 28, answer: 'leaf', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'let', position: 'after' }, { text: 'over', position: 'before' }, { text: 'gold', position: 'before' }] },
  { id: 'OU-029', level: 29, answer: 'log', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'book', position: 'after' }, { text: 'jam', position: 'after' }, { text: 'back', position: 'before' }] },
  { id: 'OU-030', level: 30, answer: 'frost', accepted: [],
    difficulty: 3, category: 'category.weather',
    words: [{ text: 'bite', position: 'after' }, { text: 'work', position: 'after' }, { text: 'de', position: 'before' }] },
  { id: 'OU-031', level: 31, answer: 'port', accepted: [],
    difficulty: 3, category: 'category.places',
    words: [{ text: 'air', position: 'before' }, { text: 'sea', position: 'before' }, { text: 'hole', position: 'after' }] },
  { id: 'OU-032', level: 32, answer: 'mud', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'slide', position: 'after' }, { text: 'guard', position: 'after' }, { text: 'bath', position: 'after' }] },
  { id: 'OU-033', level: 33, answer: 'shore', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'sea', position: 'before' }, { text: 'line', position: 'after' }, { text: 'off', position: 'before' }] },
  { id: 'OU-034', level: 34, answer: 'rock', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'bed', position: 'after' }, { text: 'slide', position: 'after' }, { text: 'sham', position: 'before' }] },
  { id: 'OU-035', level: 35, answer: 'stream', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'down', position: 'before' }, { text: 'up', position: 'before' }, { text: 'line', position: 'after' }] },
  { id: 'OU-036', level: 36, answer: 'sky', accepted: [],
    difficulty: 3, category: 'category.sky',
    words: [{ text: 'line', position: 'after' }, { text: 'lark', position: 'after' }, { text: 'scraper', position: 'after' }] },
  { id: 'OU-037', level: 37, answer: 'root', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'beet', position: 'before' }, { text: 'ginger', position: 'before' }, { text: 'less', position: 'after' }] },
  { id: 'OU-038', level: 38, answer: 'tide', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'low', position: 'before' }, { text: 'water', position: 'after' }, { text: 'high', position: 'before' }] },
  { id: 'OU-039', level: 39, answer: 'winter', accepted: [],
    difficulty: 3, category: 'category.time',
    words: [{ text: 'time', position: 'after' }, { text: 'green', position: 'after' }, { text: 'mid', position: 'before' }] },
  { id: 'OU-040', level: 40, answer: 'steam', accepted: [],
    difficulty: 3, category: 'category.nature',
    words: [{ text: 'boat', position: 'after' }, { text: 'roller', position: 'after' }, { text: 'ship', position: 'after' }] },
  { id: 'OU-041', level: 41, answer: 'flood', accepted: [],
    difficulty: 4, category: 'category.weather',
    words: [{ text: 'gate', position: 'after' }, { text: 'light', position: 'after' }, { text: 'plain', position: 'after' }] },
  { id: 'OU-042', level: 42, answer: 'dust', accepted: [],
    difficulty: 4, category: 'category.nature',
    words: [{ text: 'saw', position: 'before' }, { text: 'bin', position: 'after' }, { text: 'pan', position: 'after' }] },
  { id: 'OU-043', level: 43, answer: 'shell', accepted: [],
    difficulty: 4, category: 'category.nature',
    words: [{ text: 'sea', position: 'before' }, { text: 'fish', position: 'after' }, { text: 'nut', position: 'before' }] },
  { id: 'OU-044', level: 44, answer: 'grass', accepted: [],
    difficulty: 4, category: 'category.nature',
    words: [{ text: 'hopper', position: 'after' }, { text: 'land', position: 'after' }, { text: 'blue', position: 'before' }] },
  { id: 'OU-045', level: 45, answer: 'wave', accepted: [],
    difficulty: 4, category: 'category.nature',
    words: [{ text: 'micro', position: 'before' }, { text: 'length', position: 'after' }, { text: 'heat', position: 'before' }] },
  { id: 'OU-046', level: 46, answer: 'spring', accepted: [],
    difficulty: 4, category: 'category.nature',
    words: [{ text: 'time', position: 'after' }, { text: 'board', position: 'after' }, { text: 'off', position: 'before' }] },
  { id: 'OU-047', level: 47, answer: 'north', accepted: [],
    difficulty: 4, category: 'category.places',
    words: [{ text: 'east', position: 'after' }, { text: 'ward', position: 'after' }, { text: 'pole', position: 'after' }] },
  { id: 'OU-048', level: 48, answer: 'weed', accepted: [],
    difficulty: 4, category: 'category.nature',
    words: [{ text: 'sea', position: 'before' }, { text: 'killer', position: 'after' }, { text: 'tumble', position: 'before' }] },
  { id: 'OU-049', level: 49, answer: 'garden', accepted: [],
    difficulty: 5, category: 'category.places',
    words: [{ text: 'er', position: 'after' }, { text: 'kitchen', position: 'before' }, { text: 'roof', position: 'before' }] },
  { id: 'OU-050', level: 50, answer: 'trail', accepted: [],
    difficulty: 4, category: 'category.places',
    words: [{ text: 'blazer', position: 'after' }, { text: 'off', position: 'after' }, { text: 'nature', position: 'before' }] },
  ],
  'creatures': [
  { id: 'CR-001', level: 1, answer: 'brain', accepted: [],
    difficulty: 1, category: 'category.body',
    words: [{ text: 'storm', position: 'after' }, { text: 'wash', position: 'after' }, { text: 'child', position: 'after' }] },
  { id: 'CR-002', level: 2, answer: 'blood', accepted: [],
    difficulty: 1, category: 'category.body',
    words: [{ text: 'stream', position: 'after' }, { text: 'hound', position: 'after' }, { text: 'life', position: 'before' }] },
  { id: 'CR-003', level: 3, answer: 'pig', accepted: [],
    difficulty: 1, category: 'category.animals',
    words: [{ text: 'tail', position: 'after' }, { text: 'pen', position: 'after' }, { text: 'skin', position: 'after' }] },
  { id: 'CR-004', level: 4, answer: 'crab', accepted: [],
    difficulty: 1, category: 'category.animals',
    words: [{ text: 'apple', position: 'after' }, { text: 'meat', position: 'after' }, { text: 'grass', position: 'after' }] },
  { id: 'CR-005', level: 5, answer: 'cow', accepted: [],
    difficulty: 2, category: 'category.animals',
    words: [{ text: 'boy', position: 'after' }, { text: 'girl', position: 'after' }, { text: 'hide', position: 'after' }] },
  { id: 'CR-006', level: 6, answer: 'arm', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'chair', position: 'after' }, { text: 'pit', position: 'after' }, { text: 'band', position: 'after' }] },
  { id: 'CR-007', level: 7, answer: 'lady', accepted: [],
    difficulty: 1, category: 'category.people',
    words: [{ text: 'bug', position: 'after' }, { text: 'bird', position: 'after' }, { text: 'like', position: 'after' }] },
  { id: 'CR-008', level: 8, answer: 'crow', accepted: [],
    difficulty: 2, category: 'category.animals',
    words: [{ text: 'bar', position: 'after' }, { text: 'scare', position: 'before' }, { text: 'foot', position: 'after' }] },
  { id: 'CR-009', level: 9, answer: 'duck', accepted: [],
    difficulty: 2, category: 'category.animals',
    words: [{ text: 'ling', position: 'after' }, { text: 'weed', position: 'after' }, { text: 'board', position: 'after' }] },
  { id: 'CR-010', level: 10, answer: 'king', accepted: [],
    difficulty: 2, category: 'category.people',
    words: [{ text: 'fisher', position: 'after' }, { text: 'dom', position: 'after' }, { text: 'pin', position: 'after' }] },
  { id: 'CR-011', level: 11, answer: 'finger', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'print', position: 'after' }, { text: 'nail', position: 'after' }, { text: 'tip', position: 'after' }] },
  { id: 'CR-012', level: 12, answer: 'face', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'book', position: 'after' }, { text: 'lift', position: 'after' }, { text: 'sur', position: 'before' }] },
  { id: 'CR-013', level: 13, answer: 'hound', accepted: [],
    difficulty: 2, category: 'category.animals',
    words: [{ text: 'fox', position: 'before' }, { text: 'blood', position: 'before' }, { text: 'grey', position: 'before' }] },
  { id: 'CR-014', level: 14, answer: 'goose', accepted: [],
    difficulty: 2, category: 'category.animals',
    words: [{ text: 'bump', position: 'after' }, { text: 'berry', position: 'after' }, { text: 'neck', position: 'after' }] },
  { id: 'CR-015', level: 15, answer: 'thumb', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'nail', position: 'after' }, { text: 'tack', position: 'after' }, { text: 'screw', position: 'after' }] },
  { id: 'CR-016', level: 16, answer: 'boy', accepted: [],
    difficulty: 2, category: 'category.people',
    words: [{ text: 'cow', position: 'before' }, { text: 'friend', position: 'after' }, { text: 'bell', position: 'before' }] },
  { id: 'CR-017', level: 17, answer: 'hair', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'cut', position: 'after' }, { text: 'brush', position: 'after' }, { text: 'style', position: 'after' }] },
  { id: 'CR-018', level: 18, answer: 'nest', accepted: [],
    difficulty: 2, category: 'category.animals',
    words: [{ text: 'egg', position: 'after' }, { text: 'bird', position: 'before' }, { text: 'hornet', position: 'before' }] },
  { id: 'CR-019', level: 19, answer: 'sheep', accepted: [],
    difficulty: 2, category: 'category.animals',
    words: [{ text: 'dog', position: 'after' }, { text: 'skin', position: 'after' }, { text: 'fold', position: 'after' }] },
  { id: 'CR-020', level: 20, answer: 'lip', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'stick', position: 'after' }, { text: 'read', position: 'after' }, { text: 'sync', position: 'after' }] },
  { id: 'CR-021', level: 21, answer: 'tail', accepted: [],
    difficulty: 2, category: 'category.animals',
    words: [{ text: 'pig', position: 'before' }, { text: 'gate', position: 'after' }, { text: 'coat', position: 'after' }] },
  { id: 'CR-022', level: 22, answer: 'skin', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'pig', position: 'before' }, { text: 'deep', position: 'after' }, { text: 'sheep', position: 'before' }] },
  { id: 'CR-023', level: 23, answer: 'bone', accepted: [],
    difficulty: 3, category: 'category.body',
    words: [{ text: 'back', position: 'after' }, { text: 'dry', position: 'after' }, { text: 'wish', position: 'before' }] },
  { id: 'CR-024', level: 24, answer: 'nail', accepted: [],
    difficulty: 2, category: 'category.body',
    words: [{ text: 'finger', position: 'before' }, { text: 'thumb', position: 'before' }, { text: 'toe', position: 'before' }] },
  { id: 'CR-025', level: 25, answer: 'child', accepted: [],
    difficulty: 3, category: 'category.people',
    words: [{ text: 'hood', position: 'after' }, { text: 'brain', position: 'before' }, { text: 'proof', position: 'after' }] },
  { id: 'CR-026', level: 26, answer: 'bug', accepted: [],
    difficulty: 3, category: 'category.animals',
    words: [{ text: 'lady', position: 'before' }, { text: 'fire', position: 'before' }, { text: 'bear', position: 'after' }] },
  { id: 'CR-027', level: 27, answer: 'body', accepted: [],
    difficulty: 3, category: 'category.body',
    words: [{ text: 'every', position: 'before' }, { text: 'guard', position: 'after' }, { text: 'work', position: 'after' }] },
  { id: 'CR-028', level: 28, answer: 'ear', accepted: [],
    difficulty: 3, category: 'category.body',
    words: [{ text: 'ring', position: 'after' }, { text: 'drum', position: 'after' }, { text: 'ache', position: 'after' }] },
  { id: 'CR-029', level: 29, answer: 'fly', accepted: [],
    difficulty: 3, category: 'category.animals',
    words: [{ text: 'butter', position: 'before' }, { text: 'paper', position: 'after' }, { text: 'dragon', position: 'before' }] },
  { id: 'CR-030', level: 30, answer: 'cat', accepted: [],
    difficulty: 3, category: 'category.animals',
    words: [{ text: 'fish', position: 'after' }, { text: 'walk', position: 'after' }, { text: 'bob', position: 'before' }] },
  { id: 'CR-031', level: 31, answer: 'heart', accepted: [],
    difficulty: 3, category: 'category.body',
    words: [{ text: 'beat', position: 'after' }, { text: 'burn', position: 'after' }, { text: 'sweet', position: 'before' }] },
  { id: 'CR-032', level: 32, answer: 'frog', accepted: [],
    difficulty: 3, category: 'category.animals',
    words: [{ text: 'man', position: 'after' }, { text: 'spawn', position: 'after' }, { text: 'bull', position: 'before' }] },
  { id: 'CR-033', level: 33, answer: 'mind', accepted: [],
    difficulty: 3, category: 'category.body',
    words: [{ text: 'master', position: 'before' }, { text: 'set', position: 'after' }, { text: 'ful', position: 'after' }] },
  { id: 'CR-034', level: 34, answer: 'horn', accepted: [],
    difficulty: 3, category: 'category.animals',
    words: [{ text: 'pipe', position: 'after' }, { text: 'shoe', position: 'before' }, { text: 'long', position: 'before' }] },
  { id: 'CR-035', level: 35, answer: 'worm', accepted: [],
    difficulty: 3, category: 'category.animals',
    words: [{ text: 'earth', position: 'before' }, { text: 'hole', position: 'after' }, { text: 'wood', position: 'before' }] },
  { id: 'CR-036', level: 36, answer: 'tooth', accepted: [],
    difficulty: 3, category: 'category.body',
    words: [{ text: 'brush', position: 'after' }, { text: 'ache', position: 'after' }, { text: 'paste', position: 'after' }] },
  { id: 'CR-037', level: 37, answer: 'leg', accepted: [],
    difficulty: 3, category: 'category.body',
    words: [{ text: 'work', position: 'after' }, { text: 'room', position: 'after' }, { text: 'boot', position: 'before' }] },
  { id: 'CR-038', level: 38, answer: 'bee', accepted: [],
    difficulty: 4, category: 'category.animals',
    words: [{ text: 'hive', position: 'after' }, { text: 'keeper', position: 'after' }, { text: 'honey', position: 'before' }] },
  { id: 'CR-039', level: 39, answer: 'dog', accepted: [],
    difficulty: 4, category: 'category.animals',
    words: [{ text: 'watch', position: 'before' }, { text: 'house', position: 'after' }, { text: 'hot', position: 'before' }] },
  { id: 'CR-040', level: 40, answer: 'wolf', accepted: [],
    difficulty: 3, category: 'category.animals',
    words: [{ text: 'were', position: 'before' }, { text: 'hound', position: 'after' }, { text: 'bane', position: 'after' }] },
  { id: 'CR-041', level: 41, answer: 'fox', accepted: [],
    difficulty: 4, category: 'category.animals',
    words: [{ text: 'glove', position: 'after' }, { text: 'hole', position: 'after' }, { text: 'hound', position: 'before' }] },
  { id: 'CR-042', level: 42, answer: 'father', accepted: [],
    difficulty: 4, category: 'category.people',
    words: [{ text: 'grand', position: 'before' }, { text: 'hood', position: 'after' }, { text: 'step', position: 'before' }] },
  { id: 'CR-043', level: 43, answer: 'mouse', accepted: [],
    difficulty: 4, category: 'category.animals',
    words: [{ text: 'trap', position: 'after' }, { text: 'hole', position: 'after' }, { text: 'dor', position: 'before' }] },
  { id: 'CR-044', level: 44, answer: 'horse', accepted: [],
    difficulty: 4, category: 'category.animals',
    words: [{ text: 'sea', position: 'before' }, { text: 'shoe', position: 'after' }, { text: 'race', position: 'before' }] },
  { id: 'CR-045', level: 45, answer: 'wing', accepted: [],
    difficulty: 4, category: 'category.animals',
    words: [{ text: 'span', position: 'after' }, { text: 'nut', position: 'after' }, { text: 'tip', position: 'after' }] },
  { id: 'CR-046', level: 46, answer: 'neck', accepted: [],
    difficulty: 4, category: 'category.body',
    words: [{ text: 'lace', position: 'after' }, { text: 'tie', position: 'after' }, { text: 'bottle', position: 'before' }] },
  { id: 'CR-047', level: 47, answer: 'knee', accepted: [],
    difficulty: 4, category: 'category.body',
    words: [{ text: 'cap', position: 'after' }, { text: 'deep', position: 'after' }, { text: 'jerk', position: 'after' }] },
  { id: 'CR-048', level: 48, answer: 'mother', accepted: [],
    difficulty: 5, category: 'category.people',
    words: [{ text: 'grand', position: 'before' }, { text: 'hood', position: 'after' }, { text: 'land', position: 'after' }] },
  { id: 'CR-049', level: 49, answer: 'rat', accepted: [],
    difficulty: 5, category: 'category.animals',
    words: [{ text: 'trap', position: 'after' }, { text: 'race', position: 'after' }, { text: 'mus', position: 'before' }] },
  { id: 'CR-050', level: 50, answer: 'nose', accepted: [],
    difficulty: 4, category: 'category.body',
    words: [{ text: 'dive', position: 'after' }, { text: 'bleed', position: 'after' }, { text: 'brown', position: 'before' }] },
  ],
  'workshop': [
  { id: 'WO-001', level: 1, answer: 'craft', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'air', position: 'before' }, { text: 'hand', position: 'before' }, { text: 'ship', position: 'after' }] },
  { id: 'WO-002', level: 2, answer: 'brush', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'tooth', position: 'before' }, { text: 'hair', position: 'before' }, { text: 'paint', position: 'before' }] },
  { id: 'WO-003', level: 3, answer: 'mill', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'wind', position: 'before' }, { text: 'stone', position: 'after' }, { text: 'saw', position: 'before' }] },
  { id: 'WO-004', level: 4, answer: 'frame', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'work', position: 'after' }, { text: 'time', position: 'before' }, { text: 'door', position: 'before' }] },
  { id: 'WO-005', level: 5, answer: 'post', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'card', position: 'after' }, { text: 'man', position: 'after' }, { text: 'sign', position: 'before' }] },
  { id: 'WO-006', level: 6, answer: 'yard', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'ship', position: 'before' }, { text: 'court', position: 'before' }, { text: 'stick', position: 'after' }] },
  { id: 'WO-007', level: 7, answer: 'glass', accepted: [],
    difficulty: 1, category: 'category.material',
    words: [{ text: 'hour', position: 'before' }, { text: 'house', position: 'after' }, { text: 'eye', position: 'before' }] },
  { id: 'WO-008', level: 8, answer: 'rail', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'road', position: 'after' }, { text: 'way', position: 'after' }, { text: 'hand', position: 'before' }] },
  { id: 'WO-009', level: 9, answer: 'rubber', accepted: [],
    difficulty: 1, category: 'category.material',
    words: [{ text: 'band', position: 'after' }, { text: 'neck', position: 'after' }, { text: 'stamp', position: 'after' }] },
  { id: 'WO-010', level: 10, answer: 'pipe', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'line', position: 'after' }, { text: 'dream', position: 'after' }, { text: 'horn', position: 'before' }] },
  { id: 'WO-011', level: 11, answer: 'paint', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'brush', position: 'after' }, { text: 'ball', position: 'after' }, { text: 'work', position: 'after' }] },
  { id: 'WO-012', level: 12, answer: 'ship', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'friend', position: 'before' }, { text: 'yard', position: 'after' }, { text: 'war', position: 'before' }] },
  { id: 'WO-013', level: 13, answer: 'bolt', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'thunder', position: 'before' }, { text: 'lock', position: 'before' }, { text: 'cutter', position: 'after' }] },
  { id: 'WO-014', level: 14, answer: 'lift', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'fork', position: 'before' }, { text: 'shop', position: 'before' }, { text: 'off', position: 'after' }] },
  { id: 'WO-015', level: 15, answer: 'gear', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'box', position: 'after' }, { text: 'shift', position: 'after' }, { text: 'head', position: 'before' }] },
  { id: 'WO-016', level: 16, answer: 'cart', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'wheel', position: 'before' }, { text: 'horse', position: 'before' }, { text: 'load', position: 'after' }] },
  { id: 'WO-017', level: 17, answer: 'beam', accepted: [],
    difficulty: 2, category: 'category.material',
    words: [{ text: 'moon', position: 'before' }, { text: 'sun', position: 'before' }, { text: 'cross', position: 'before' }] },
  { id: 'WO-018', level: 18, answer: 'gun', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'shot', position: 'after' }, { text: 'fire', position: 'after' }, { text: 'powder', position: 'after' }] },
  { id: 'WO-019', level: 19, answer: 'battle', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'field', position: 'after' }, { text: 'ship', position: 'after' }, { text: 'axe', position: 'after' }] },
  { id: 'WO-020', level: 20, answer: 'chain', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'saw', position: 'after' }, { text: 'mail', position: 'after' }, { text: 'key', position: 'before' }] },
  { id: 'WO-021', level: 21, answer: 'press', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'news', position: 'before' }, { text: 'up', position: 'after' }, { text: 'ing', position: 'after' }] },
  { id: 'WO-022', level: 22, answer: 'mark', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'book', position: 'before' }, { text: 'land', position: 'before' }, { text: 'trade', position: 'before' }] },
  { id: 'WO-023', level: 23, answer: 'site', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'camp', position: 'before' }, { text: 'web', position: 'before' }, { text: 'work', position: 'before' }] },
  { id: 'WO-024', level: 24, answer: 'shop', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'work', position: 'before' }, { text: 'keeper', position: 'after' }, { text: 'lift', position: 'after' }] },
  { id: 'WO-025', level: 25, answer: 'store', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'house', position: 'after' }, { text: 'room', position: 'after' }, { text: 'keeper', position: 'after' }] },
  { id: 'WO-026', level: 26, answer: 'stamp', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'rubber', position: 'before' }, { text: 'ede', position: 'after' }, { text: 'foot', position: 'before' }] },
  { id: 'WO-027', level: 27, answer: 'shot', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'screen', position: 'before' }, { text: 'gun', position: 'after' }, { text: 'snap', position: 'before' }] },
  { id: 'WO-028', level: 28, answer: 'tool', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'box', position: 'after' }, { text: 'bar', position: 'after' }, { text: 'kit', position: 'after' }] },
  { id: 'WO-029', level: 29, answer: 'trade', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'mark', position: 'after' }, { text: 'off', position: 'after' }, { text: 'man', position: 'after' }] },
  { id: 'WO-030', level: 30, answer: 'stick', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'yard', position: 'before' }, { text: 'chop', position: 'before' }, { text: 'lip', position: 'before' }] },
  { id: 'WO-031', level: 31, answer: 'wheel', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'barrow', position: 'after' }, { text: 'chair', position: 'after' }, { text: 'cart', position: 'before' }] },
  { id: 'WO-032', level: 32, answer: 'walk', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'side', position: 'before' }, { text: 'way', position: 'after' }, { text: 'board', position: 'before' }] },
  { id: 'WO-033', level: 33, answer: 'iron', accepted: [],
    difficulty: 3, category: 'category.material',
    words: [{ text: 'work', position: 'after' }, { text: 'cast', position: 'before' }, { text: 'clad', position: 'after' }] },
  { id: 'WO-034', level: 34, answer: 'band', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'rubber', position: 'before' }, { text: 'wide', position: 'before' }, { text: 'wagon', position: 'after' }] },
  { id: 'WO-035', level: 35, answer: 'net', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'work', position: 'after' }, { text: 'ball', position: 'after' }, { text: 'inter', position: 'before' }] },
  { id: 'WO-036', level: 36, answer: 'metal', accepted: [],
    difficulty: 3, category: 'category.material',
    words: [{ text: 'work', position: 'after' }, { text: 'sheet', position: 'before' }, { text: 'heavy', position: 'before' }] },
  { id: 'WO-037', level: 37, answer: 'brick', accepted: [],
    difficulty: 3, category: 'category.material',
    words: [{ text: 'work', position: 'after' }, { text: 'layer', position: 'after' }, { text: 'red', position: 'before' }] },
  { id: 'WO-038', level: 38, answer: 'pin', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'king', position: 'before' }, { text: 'cushion', position: 'after' }, { text: 'point', position: 'after' }] },
  { id: 'WO-039', level: 39, answer: 'saw', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'mill', position: 'after' }, { text: 'dust', position: 'after' }, { text: 'chain', position: 'before' }] },
  { id: 'WO-040', level: 40, answer: 'motor', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'bike', position: 'after' }, { text: 'way', position: 'after' }, { text: 'cade', position: 'after' }] },
  { id: 'WO-041', level: 41, answer: 'screw', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'driver', position: 'after' }, { text: 'ball', position: 'after' }, { text: 'cork', position: 'before' }] },
  { id: 'WO-042', level: 42, answer: 'screen', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'wind', position: 'before' }, { text: 'play', position: 'after' }, { text: 'shot', position: 'after' }] },
  { id: 'WO-043', level: 43, answer: 'switch', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'board', position: 'after' }, { text: 'blade', position: 'after' }, { text: 'over', position: 'after' }] },
  { id: 'WO-044', level: 44, answer: 'sign', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'post', position: 'after' }, { text: 'board', position: 'after' }, { text: 'de', position: 'before' }] },
  { id: 'WO-045', level: 45, answer: 'lock', accepted: [],
    difficulty: 4, category: 'category.things',
    words: [{ text: 'pad', position: 'after' }, { text: 'smith', position: 'after' }, { text: 'dead', position: 'before' }] },
  { id: 'WO-046', level: 46, answer: 'tank', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'top', position: 'after' }, { text: 'er', position: 'after' }, { text: 'think', position: 'before' }] },
  { id: 'WO-047', level: 47, answer: 'steel', accepted: [],
    difficulty: 3, category: 'category.material',
    words: [{ text: 'work', position: 'after' }, { text: 'wool', position: 'after' }, { text: 'stain', position: 'before' }] },
  { id: 'WO-048', level: 48, answer: 'plug', accepted: [],
    difficulty: 4, category: 'category.things',
    words: [{ text: 'un', position: 'before' }, { text: 'hole', position: 'after' }, { text: 'spark', position: 'before' }] },
  { id: 'WO-049', level: 49, answer: 'wire', accepted: [],
    difficulty: 4, category: 'category.material',
    words: [{ text: 'tap', position: 'after' }, { text: 'less', position: 'after' }, { text: 'hay', position: 'before' }] },
  { id: 'WO-050', level: 50, answer: 'hammer', accepted: [],
    difficulty: 4, category: 'category.things',
    words: [{ text: 'sledge', position: 'before' }, { text: 'head', position: 'after' }, { text: 'jack', position: 'before' }] },
  ],
  'nightfall': [
  { id: 'NI-001', level: 1, answer: 'court', accepted: [],
    difficulty: 1, category: 'category.places',
    words: [{ text: 'yard', position: 'after' }, { text: 'house', position: 'after' }, { text: 'room', position: 'after' }] },
  { id: 'NI-002', level: 2, answer: 'chair', accepted: [],
    difficulty: 1, category: 'category.home',
    words: [{ text: 'arm', position: 'before' }, { text: 'wheel', position: 'before' }, { text: 'man', position: 'after' }] },
  { id: 'NI-003', level: 3, answer: 'guest', accepted: [],
    difficulty: 1, category: 'category.home',
    words: [{ text: 'house', position: 'after' }, { text: 'room', position: 'after' }, { text: 'book', position: 'after' }] },
  { id: 'NI-004', level: 4, answer: 'door', accepted: [],
    difficulty: 1, category: 'category.home',
    words: [{ text: 'bell', position: 'after' }, { text: 'way', position: 'after' }, { text: 'out', position: 'before' }] },
  { id: 'NI-005', level: 5, answer: 'mid', accepted: [],
    difficulty: 1, category: 'category.time',
    words: [{ text: 'night', position: 'after' }, { text: 'way', position: 'after' }, { text: 'summer', position: 'after' }] },
  { id: 'NI-006', level: 6, answer: 'hall', accepted: [],
    difficulty: 1, category: 'category.home',
    words: [{ text: 'way', position: 'after' }, { text: 'mark', position: 'after' }, { text: 'town', position: 'before' }] },
  { id: 'NI-007', level: 7, answer: 'glow', accepted: [],
    difficulty: 1, category: 'category.time',
    words: [{ text: 'worm', position: 'after' }, { text: 'after', position: 'before' }, { text: 'stick', position: 'after' }] },
  { id: 'NI-008', level: 8, answer: 'print', accepted: [],
    difficulty: 1, category: 'category.things',
    words: [{ text: 'foot', position: 'before' }, { text: 'finger', position: 'before' }, { text: 'out', position: 'after' }] },
  { id: 'NI-009', level: 9, answer: 'shade', accepted: [],
    difficulty: 1, category: 'category.home',
    words: [{ text: 'sun', position: 'before' }, { text: 'night', position: 'before' }, { text: 'lamp', position: 'before' }] },
  { id: 'NI-010', level: 10, answer: 'lamp', accepted: [],
    difficulty: 1, category: 'category.home',
    words: [{ text: 'post', position: 'after' }, { text: 'shade', position: 'after' }, { text: 'light', position: 'before' }] },
  { id: 'NI-011', level: 11, answer: 'bath', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'room', position: 'after' }, { text: 'tub', position: 'after' }, { text: 'blood', position: 'before' }] },
  { id: 'NI-012', level: 12, answer: 'wall', accepted: [],
    difficulty: 1, category: 'category.home',
    words: [{ text: 'paper', position: 'after' }, { text: 'flower', position: 'after' }, { text: 'fire', position: 'before' }] },
  { id: 'NI-013', level: 13, answer: 'dark', accepted: [],
    difficulty: 2, category: 'category.time',
    words: [{ text: 'room', position: 'after' }, { text: 'ness', position: 'after' }, { text: 'after', position: 'before' }] },
  { id: 'NI-014', level: 14, answer: 'bed', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'room', position: 'after' }, { text: 'time', position: 'after' }, { text: 'flower', position: 'before' }] },
  { id: 'NI-015', level: 15, answer: 'letter', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'news', position: 'before' }, { text: 'box', position: 'after' }, { text: 'head', position: 'after' }] },
  { id: 'NI-016', level: 16, answer: 'home', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'town', position: 'after' }, { text: 'work', position: 'after' }, { text: 'sick', position: 'after' }] },
  { id: 'NI-017', level: 17, answer: 'bell', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'blue', position: 'before' }, { text: 'boy', position: 'after' }, { text: 'door', position: 'before' }] },
  { id: 'NI-018', level: 18, answer: 'ring', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'ear', position: 'before' }, { text: 'tone', position: 'after' }, { text: 'leader', position: 'after' }] },
  { id: 'NI-019', level: 19, answer: 'noon', accepted: [],
    difficulty: 2, category: 'category.time',
    words: [{ text: 'after', position: 'before' }, { text: 'fore', position: 'before' }, { text: 'day', position: 'before' }] },
  { id: 'NI-020', level: 20, answer: 'ink', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'well', position: 'after' }, { text: 'blot', position: 'after' }, { text: 'pot', position: 'after' }] },
  { id: 'NI-021', level: 21, answer: 'set', accepted: [],
    difficulty: 2, category: 'category.time',
    words: [{ text: 'sun', position: 'before' }, { text: 'mind', position: 'before' }, { text: 'back', position: 'after' }] },
  { id: 'NI-022', level: 22, answer: 'note', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'book', position: 'after' }, { text: 'foot', position: 'before' }, { text: 'pad', position: 'after' }] },
  { id: 'NI-023', level: 23, answer: 'news', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'paper', position: 'after' }, { text: 'cast', position: 'after' }, { text: 'letter', position: 'after' }] },
  { id: 'NI-024', level: 24, answer: 'read', accepted: [],
    difficulty: 2, category: 'category.time',
    words: [{ text: 'lip', position: 'before' }, { text: 'proof', position: 'before' }, { text: 'out', position: 'after' }] },
  { id: 'NI-025', level: 25, answer: 'soft', accepted: [],
    difficulty: 2, category: 'category.time',
    words: [{ text: 'ware', position: 'after' }, { text: 'wood', position: 'after' }, { text: 'ball', position: 'after' }] },
  { id: 'NI-026', level: 26, answer: 'page', accepted: [],
    difficulty: 2, category: 'category.things',
    words: [{ text: 'home', position: 'before' }, { text: 'boy', position: 'after' }, { text: 'ram', position: 'before' }] },
  { id: 'NI-027', level: 27, answer: 'rest', accepted: [],
    difficulty: 2, category: 'category.time',
    words: [{ text: 'less', position: 'after' }, { text: 'room', position: 'after' }, { text: 'bed', position: 'before' }] },
  { id: 'NI-028', level: 28, answer: 'stair', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'up', position: 'before' }, { text: 'down', position: 'before' }, { text: 'case', position: 'after' }] },
  { id: 'NI-029', level: 29, answer: 'step', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'door', position: 'before' }, { text: 'foot', position: 'before' }, { text: 'ladder', position: 'after' }] },
  { id: 'NI-030', level: 30, answer: 'short', accepted: [],
    difficulty: 2, category: 'category.time',
    words: [{ text: 'hand', position: 'after' }, { text: 'cut', position: 'after' }, { text: 'bread', position: 'after' }] },
  { id: 'NI-031', level: 31, answer: 'story', accepted: [],
    difficulty: 2, category: 'category.time',
    words: [{ text: 'book', position: 'after' }, { text: 'teller', position: 'after' }, { text: 'line', position: 'after' }] },
  { id: 'NI-032', level: 32, answer: 'stool', accepted: [],
    difficulty: 2, category: 'category.home',
    words: [{ text: 'foot', position: 'before' }, { text: 'toad', position: 'before' }, { text: 'bar', position: 'before' }] },
  { id: 'NI-033', level: 33, answer: 'after', accepted: [],
    difficulty: 3, category: 'category.time',
    words: [{ text: 'noon', position: 'after' }, { text: 'math', position: 'after' }, { text: 'thought', position: 'after' }] },
  { id: 'NI-034', level: 34, answer: 'town', accepted: [],
    difficulty: 2, category: 'category.places',
    words: [{ text: 'home', position: 'before' }, { text: 'down', position: 'before' }, { text: 'ship', position: 'after' }] },
  { id: 'NI-035', level: 35, answer: 'floor', accepted: [],
    difficulty: 3, category: 'category.home',
    words: [{ text: 'board', position: 'after' }, { text: 'ground', position: 'before' }, { text: 'dance', position: 'before' }] },
  { id: 'NI-036', level: 36, answer: 'clock', accepted: [],
    difficulty: 3, category: 'category.time',
    words: [{ text: 'wise', position: 'after' }, { text: 'work', position: 'after' }, { text: 'o', position: 'before' }] },
  { id: 'NI-037', level: 37, answer: 'write', accepted: [],
    difficulty: 2, category: 'category.time',
    words: [{ text: 'up', position: 'after' }, { text: 'under', position: 'before' }, { text: 'off', position: 'after' }] },
  { id: 'NI-038', level: 38, answer: 'hour', accepted: [],
    difficulty: 3, category: 'category.time',
    words: [{ text: 'glass', position: 'after' }, { text: 'half', position: 'before' }, { text: 'rush', position: 'before' }] },
  { id: 'NI-039', level: 39, answer: 'peace', accepted: [],
    difficulty: 3, category: 'category.time',
    words: [{ text: 'keeper', position: 'after' }, { text: 'maker', position: 'after' }, { text: 'time', position: 'after' }] },
  { id: 'NI-040', level: 40, answer: 'dream', accepted: [],
    difficulty: 3, category: 'category.time',
    words: [{ text: 'day', position: 'before' }, { text: 'land', position: 'after' }, { text: 'catcher', position: 'after' }] },
  { id: 'NI-041', level: 41, answer: 'pillow', accepted: [],
    difficulty: 3, category: 'category.home',
    words: [{ text: 'case', position: 'after' }, { text: 'talk', position: 'after' }, { text: 'fight', position: 'after' }] },
  { id: 'NI-042', level: 42, answer: 'pen', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'knife', position: 'after' }, { text: 'name', position: 'after' }, { text: 'play', position: 'before' }] },
  { id: 'NI-043', level: 43, answer: 'song', accepted: [],
    difficulty: 3, category: 'category.time',
    words: [{ text: 'bird', position: 'before' }, { text: 'writer', position: 'after' }, { text: 'swan', position: 'before' }] },
  { id: 'NI-044', level: 44, answer: 'shadow', accepted: [],
    difficulty: 3, category: 'category.time',
    words: [{ text: 'over', position: 'before' }, { text: 'box', position: 'after' }, { text: 'play', position: 'after' }] },
  { id: 'NI-045', level: 45, answer: 'bunk', accepted: [],
    difficulty: 4, category: 'category.home',
    words: [{ text: 'bed', position: 'after' }, { text: 'house', position: 'after' }, { text: 'de', position: 'before' }] },
  { id: 'NI-046', level: 46, answer: 'torch', accepted: [],
    difficulty: 3, category: 'category.things',
    words: [{ text: 'light', position: 'after' }, { text: 'blow', position: 'before' }, { text: 'bearer', position: 'after' }] },
  { id: 'NI-047', level: 47, answer: 'sleep', accepted: [],
    difficulty: 3, category: 'category.time',
    words: [{ text: 'over', position: 'after' }, { text: 'walker', position: 'after' }, { text: 'less', position: 'after' }] },
  { id: 'NI-048', level: 48, answer: 'school', accepted: [],
    difficulty: 4, category: 'category.places',
    words: [{ text: 'pre', position: 'before' }, { text: 'boy', position: 'after' }, { text: 'master', position: 'after' }] },
  { id: 'NI-049', level: 49, answer: 'window', accepted: [],
    difficulty: 5, category: 'category.home',
    words: [{ text: 'pane', position: 'after' }, { text: 'sill', position: 'after' }, { text: 'bay', position: 'before' }] },
  { id: 'NI-050', level: 50, answer: 'under', accepted: [],
    difficulty: 3, category: 'category.places',
    words: [{ text: 'stand', position: 'after' }, { text: 'ground', position: 'after' }, { text: 'wear', position: 'after' }] },
  ],
};
